name: Register Buildpack

on:
  issues:
    types: [opened]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      buildpack: ${{ steps.detect_validate.outputs }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        working-directory: scripts/detect
        shell: bash
        run: |
          npm install
      - name: Detect and Validate Issue
        id: detect_validate
        uses: actions/github-script@v2
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const path = require('path')
            const scriptsPath = path.resolve('scripts/detect/index.js')
            const scripts = require(scriptsPath)
            const result = scripts.validateIssue({context})

            return JSON.stringify(result)
  authenticate:
    runs-on: ubuntu-latest
    needs: detect
    steps:
      - name: Authenticate
        run: echo ${{needs.detect.outputs.buildpack}}
