name: Register Buildpack

on:
  issues:
    types: [opened]

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      buildpack: ${{ steps.detect_validate.outputs.buildpack }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        working-directory: scripts/validate
        shell: bash
        run: |
          npm install
      - id: detect_validate
        name: Validate Buildpack Registry Issue
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const path = require('path')
            const scripts = require(path.resolve('./scripts/validate/index.js'))
            const result = scripts.validateIssue({context})

            console.log(`::set-output name=buildpack::${JSON.stringify(result)}`)
  authenticate:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/github-script@v2
        name: Retrieve Owners
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        with:
          github-token: ${{ secrets.BUILDPACK_REGISTRY_GITHUB_ACTION_TOKEN }}
          script: |
            const buildpackInfo = ${{ needs.validate.outputs.buildpack }}
            let registryOwners = ''
            try {
              const {data} = await github.repos.getContents({
                owner: 'elbandito',
                path: `v1/${buildpackInfo.ns}.json`,
                repo: 'buildpack-namespaces'
              })
              const buff = new Buffer.from(data.content, 'base64')
              registryOwners = buff.toString('utf-8')

            } catch (error) {
              if (error.status && error.status === 404) {
                console.error('Creating file since it does not exist')
                const content = {
                  owners: [
                    {
                      id: context.payload.sender.id,
                      type: 'github_user'
                    }
                  ]
                };
                const buff = Buffer.from(JSON.stringify(content), 'utf-8');
                registryOwners = buff.toString('utf-8')

                await github.repos.createOrUpdateFile({
                  owner: 'elbandito',
                  repo: 'buildpack-namespaces',
                  path: `v1/${buildpackInfo.ns}.json`,
                  message: 'initial commit',
                  content: buff.toString('base64'),
                  committer: {
                    name: 'elbandito',
                    email: 'longoria.public@gmail.com'
                  },
                  author: {
                    name: 'elbandito',
                    email: 'longoria.public@gmail.com'
                  }
                })
              } else {
                console.error(error)
                process.exit(1)
              }
            }
            console.log(`::set-env name=REGISTRY_OWNERS::${registryOwners.replace(/\r?\n|\r/g, " ")}`)

      - uses: actions/github-script@v2
        name: Authenticate
        with:
          github-token: ${{ secrets.BUILDPACK_REGISTRY_GITHUB_ACTION_TOKEN }}
          script: |
            const owners = JSON.parse(process.env.REGISTRY_OWNERS).owners
            if (!!owners.find(owner => (owner.id === context.payload.sender.id) && (owner.type === 'github_user'))) {
              console.error('user successfully authenticated via github_user')
              process.exit(0)
            }

            let orgIDs = [];
            try {
              const orgs = await github.orgs.listForUser({
                username: context.payload.sender.login
              });
              orgIDs = orgs.data.map(org => org.id);

            } catch (error) {
              console.error(error);
              process.exit(1);
            }

            const filteredOwners = owners.filter(owner => (owner.type === 'github_org' && orgIDs.includes(owner.id)));
            if (filteredOwners.length > 0) {
              console.error('user successfully authenticated via github_org')
              process.exit(0)
            }

            console.error('user is NOT authorized to register buildpack')
            process.exit(1)
