name: Register Buildpack

on:
  issues:
    types: [opened]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      buildpack: ${{ steps.detect_validate.outputs.test }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        working-directory: scripts/detect
        shell: bash
        run: |
          npm install
      - id: detect_validate
        name: Detect and Validate Issue
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const path = require('path')
            const scriptsPath = path.resolve('scripts/detect/index.js')
            const scripts = require(scriptsPath)
            const result = scripts.validateIssue({context})

            console.log(`::set-output name=test::${JSON.stringify(result)}`)
  authenticate:
    runs-on: ubuntu-latest
    needs: detect
    steps:
    - name: Authenticate
      run: echo ${{needs.detect.outputs.buildpack}}
