name: Register Buildpack

on:
  issues:
    types: [opened]

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      buildpack: ${{ steps.detect_validate.outputs.buildpack }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        working-directory: scripts/detect
        shell: bash
        run: |
          npm install
      - id: detect_validate
        name: Detect and Validate Issue
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const path = require('path')
            const scripts = require(path.resolve('scripts/detect/index.js'))
            const result = scripts.validateIssue({context})

            console.log(`::set-output name=buildpack::${JSON.stringify(result)}`)
  authenticate:
    runs-on: ubuntu-latest
#    needs: detect
    steps:
      - uses: actions/github-script@v2
        name: Authenticate
        env:
          GITHUB_CONTEXT: ${{toJson(github)}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log(process.env.BUILDPACK_OUTPUT)
            github.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'test title',
                body: '👋 Thanks for reporting!'
            })
#            echo ${{needs.detect.outputs.buildpack}}
