name: Register Buildpack

on:
  issues:
    types: [opened]

jobs:
  register:
    env:
      NAMESPACE_REPO: buildpack-namespaces
      GITHUB_OWNER: elbandito
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node Dependencies
        working-directory: .github/workflows/scripts/validate
        shell: bash
        run: |
          npm install
      - id: detect_validate
        name: Validate Buildpack Issue
        uses: actions/github-script@v2
        with:
          result-encoding: string
          script: |
            const path = require('path')
            const scripts = require(path.resolve('.github/workflows/scripts/validate/index.js'))
            let result
            try {
              result = scripts.validateIssue({context})
            } catch (error) {
              console.error(error)
              process.exit(1)
            }
            console.log(`::set-env name=BUILDPACK::${JSON.stringify(result)}`)

      - uses: actions/github-script@v2
        name: Retrieve Owners
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const buildpackInfo = JSON.parse(process.env.BUILDPACK)
            let registryOwners = ''
            try {
              const {data} = await github.repos.getContent({
                owner: process.env.GITHUB_OWNER,
                path: `v1/${buildpackInfo.ns}.json`,
                repo: process.env.NAMESPACE_REPO
              })
              const buff = new Buffer.from(data.content, 'base64')
              registryOwners = buff.toString('utf-8')

            } catch (error) {
              if (error.status && error.status === 404) {
                console.error('Creating file since it does not exist')
                const content = {
                  owners: [
                    {
                      id: context.payload.sender.id,
                      type: 'github_user'
                    }
                  ]
                };
                const buff = Buffer.from(JSON.stringify(content), 'utf-8');
                registryOwners = buff.toString('utf-8')

                await github.repos.createOrUpdateFile({
                  owner: process.env.GITHUB_OWNER,
                  repo: process.env.NAMESPACE_REPO,
                  path: `v1/${buildpackInfo.ns}.json`,
                  message: 'initial commit',
                  content: buff.toString('base64'),
                  committer: {
                    name: process.env.GITHUB_OWNER,
                    email: 'longoria.public@gmail.com'
                  },
                  author: {
                    name: process.env.GITHUB_OWNER,
                    email: 'longoria.public@gmail.com'
                  }
                })
              } else {
                console.error(error)
                process.exit(1)
              }
            }
            console.log(`::set-env name=REGISTRY_OWNERS::${registryOwners.replace(/\r?\n|\r/g, " ")}`)

      - uses: actions/github-script@v2
        name: Authenticate
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const owners = JSON.parse(process.env.REGISTRY_OWNERS).owners
            if (!!owners.find(owner => (owner.id === context.payload.sender.id) && (owner.type === 'github_user'))) {
              console.error('user successfully authenticated via github_user')
              process.exit(0)
            }

            let orgIDs = [];
            try {
              const orgs = await github.orgs.listForUser({
                username: context.payload.sender.login
              });
              orgIDs = orgs.data.map(org => org.id);

            } catch (error) {
              console.error(error);
              process.exit(1);
            }

            const filteredOwners = owners.filter(owner => (owner.type === 'github_org' && orgIDs.includes(owner.id)));
            if (filteredOwners.length > 0) {
              console.error('user successfully authenticated via github_org')
              process.exit(0)
            }

            console.error('user is NOT authorized to register buildpack')
            process.exit(1)

      - uses: actions/github-script@v2
        name: Update Registry Index
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            const Path = require('path');
            const buildpackInfo = JSON.parse(process.env.BUILDPACK)
            const nameLength = buildpackInfo.name.length

            const toBase64 = (value) => {
              const buff = Buffer.from(value, 'utf-8');
              return buff.toString('base64');
            }

            const createOrUpdateFileContents = async (path, message, content, sha = '') => {
              let params = {
                owner: process.env.GITHUB_OWNER,
                repo: 'buildpack-registry',
                path,
                message,
                content,
                committer: {
                    name: process.env.GITHUB_OWNER,
                    email: 'longoria.public@gmail.com'
                },
                author: {
                    name: process.env.GITHUB_OWNER,
                    email: 'longoria.public@gmail.com'
                }
              }
              if (sha !== '') {
                  params = {...params, ...{sha}};
              }
              try {
                await github.repos.createOrUpdateFileContents(params)
              } catch (error) {
                console.error(error)
                process.exit(1)
              }
            }

            let indexPath = Path.join('index')
            if (nameLength === 1) {
                indexPath = Path.join(indexPath, '1')
            } else if (nameLength === 2) {
                indexPath = Path.join(indexPath, '2')
            } else if (nameLength === 3) {
                indexPath = Path.join(indexPath, '3', buildpackInfo.name.slice(0, 2))
            } else if (nameLength > 3) {
                indexPath = Path.join(indexPath, buildpackInfo.name.slice(0, 2), buildpackInfo.name.slice(2, 4))
            } else {
                console.error(`buildpack name cannot be empty`)
                process.exit(1)
            }

            indexPath = Path.join(indexPath, `${buildpackInfo.ns}_${buildpackInfo.name}`)
            try {
              const {data} = await github.repos.getContent({
                owner: process.env.GITHUB_OWNER,
                path: indexPath,
                repo: 'buildpack-registry'
              })

              let buff = new Buffer.from(data.content, 'base64')
              let fileContent = buff.toString('utf-8').trimEnd()
              fileContent = fileContent + "\n" + JSON.stringify(buildpackInfo)

              await createOrUpdateFileContents(indexPath, context.payload.issue.title, toBase64(fileContent), data.sha)

              } catch (error) {
                if (error.status && error.status === 404) {
                  await createOrUpdateFileContents(indexPath, context.payload.issue.title, toBase64(JSON.stringify(buildpackInfo)))
                } else {
                  console.error(error)
                  process.exit(1)
                }
              }

      - uses: actions/github-script@v2
        name: Close Issue on Success
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            try {
              await github.issues.createLabel({
                owner: process.env.GITHUB_OWNER,
                repo: 'buildpack-registry',
                name: 'succeeded',
                color: '008000'
              });
            } catch (error) {
              if (!error.errors.find(err => err.code === 'already_exists')) {
                console.error(error)
                process.exit(1)
              }
            }
            await github.issues.addLabels({
              owner: process.env.GITHUB_OWNER,
              repo: 'buildpack-registry',
              issue_number: context.payload.issue.number,
              labels: ['succeeded']
            });
            await github.issues.update({
              owner: process.env.GITHUB_OWNER,
              repo: 'buildpack-registry',
              issue_number: context.payload.issue.number,
              state: 'closed'
            })

      - uses: actions/github-script@v2
        name: Close Issue on Failure
        if: ${{ failure() }}
        with:
          github-token: ${{ secrets.BOT_TOKEN }}
          script: |
            try {
              await github.issues.createLabel({
                owner: process.env.GITHUB_OWNER,
                repo: 'buildpack-registry',
                name: 'failed',
                color: 'FF0000'
              });
            } catch (error) {
              if (!error.errors.find(err => err.code === 'already_exists')) {
                console.error(error)
                process.exit(1)
              }
            }
            await github.issues.addLabels({
              owner: process.env.GITHUB_OWNER,
              repo: 'buildpack-registry',
              issue_number: context.payload.issue.number,
              labels: ['failed']
            });
            await github.issues.update({
              owner: process.env.GITHUB_OWNER,
              repo: 'buildpack-registry',
              issue_number: context.payload.issue.number,
              state: 'closed'
            })
